const componentGenerator = require('./Component.js')
const containerGenerator = require('./Container.js')
const reduxInitGenerator = require('./ReduxInit.js')
const reduxEntityGenerator = require('./ReduxEntity.js')
const reduxActionGenerator = require('./ReduxAction.js')
const sagasInitGenerator = require('./SagasInit.js')
const sagaEntityGenerator = require('./SagaEntity.js')
const sagaActionGenerator = require('./SagaAction.js')
const stateToPropsGenerator = require('./StateToProps.js')

module.exports = (plop) => {
  plop.setGenerator('component', componentGenerator)
  plop.setGenerator('container', containerGenerator)
  plop.setGenerator('redux init', reduxInitGenerator)
  plop.setGenerator('redux entity', reduxEntityGenerator)
  plop.setGenerator('redux action', reduxActionGenerator)
  plop.setGenerator('sagas init', sagasInitGenerator)
  plop.setGenerator('saga entity', sagaEntityGenerator)
  plop.setGenerator('saga action', sagaActionGenerator)
  plop.setGenerator('state to props', stateToPropsGenerator)
}
